pipeline {
    agent any
    stages {

        stage('pull') {
            steps {
                git url: 'https://github.com/Varunkumar2698/Amazon.git'
            }
        }
            
        stage('build') {
            steps {
                 sh 'cd Amazon && mvn clean install'
            }
        }
        stage('deploy to dev environment') {
            steps {
    
                sh '/home/varun/Desktop/files/Dev_environment/apache-tomcat-9.0.86/bin/startup.sh'
                

            }
        }
    }
  post{
    always {
        archieveArtifacts artifacts: '**/target/*.war'
        deploy adapters: [tomcat9(credentialsId: '9551387d-fc2a-401d-b340-7a8290e60ef6', path: '', url: 'http://localhost:8085/manager/html')], contextPath: 'Amazon', war: '**/target/*.war'
    }

  }


}
